services:
  drupal:
    image: custom_drupal
    build: .
    volumes:
      - ./modules:/var/www/html/modules
      - ./profiles:/var/www/html/profiles
      - ./themes:/var/www/html/themes
      - drupal-sites:/var/www/html/sites
    ports:
      - "8083:80"
      - "3000:3000"
      - "3001:3001"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: user
      POSTGRES_PASSWORD: drupal
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always

  adminer:
    image: adminer
    ports:
      - "8081:8080"
    depends_on:
      - db
    restart: always

volumes:
  drupal-sites: